services:
  web-test:
    build:
      context: ./infrastructure/docker/web
      dockerfile: Dockerfile
    container_name: web-test
    ports:
      - "8181:80"
    volumes:
      - .:/var/www/html
    networks:
      - skeleton-test
    depends_on:
      - database-test

  database-test:
    image: mysql:8.0
    container_name: database-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql2
    networks:
      - skeleton-test

volumes:
  db_data:

networks:
  skeleton-test:
    driver: bridge
