services:
  web:
    build:
      context: ./infrastructure/docker/web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - skeleton
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - skeleton

volumes:
  db_data:

networks:
  skeleton:
    driver: bridge
